/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MypageSettingsRouteImport } from './routes/mypage/settings'
import { Route as MypageProfileRouteImport } from './routes/mypage/profile'
import { Route as MypageNotificationsRouteImport } from './routes/mypage/notifications'
import { Route as MypageLayoutRouteImport } from './routes/mypage/_layout'
import { Route as appMyProfileRouteImport } from './routes/(app)/my-profile'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageSettingsRoute = MypageSettingsRouteImport.update({
  id: '/mypage/settings',
  path: '/mypage/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageProfileRoute = MypageProfileRouteImport.update({
  id: '/mypage/profile',
  path: '/mypage/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageNotificationsRoute = MypageNotificationsRouteImport.update({
  id: '/mypage/notifications',
  path: '/mypage/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageLayoutRoute = MypageLayoutRouteImport.update({
  id: '/mypage/_layout',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const appMyProfileRoute = appMyProfileRouteImport.update({
  id: '/(app)/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/my-profile': typeof appMyProfileRoute
  '/mypage': typeof MypageLayoutRoute
  '/mypage/notifications': typeof MypageNotificationsRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/settings': typeof MypageSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/my-profile': typeof appMyProfileRoute
  '/mypage': typeof MypageLayoutRoute
  '/mypage/notifications': typeof MypageNotificationsRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/settings': typeof MypageSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_layout': typeof appLayoutRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/my-profile': typeof appMyProfileRoute
  '/mypage/_layout': typeof MypageLayoutRoute
  '/mypage/notifications': typeof MypageNotificationsRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/settings': typeof MypageSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/my-profile'
    | '/mypage'
    | '/mypage/notifications'
    | '/mypage/profile'
    | '/mypage/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/my-profile'
    | '/mypage'
    | '/mypage/notifications'
    | '/mypage/profile'
    | '/mypage/settings'
  id:
    | '__root__'
    | '/'
    | '/(app)/_layout'
    | '/(app)/dashboard'
    | '/(app)/my-profile'
    | '/mypage/_layout'
    | '/mypage/notifications'
    | '/mypage/profile'
    | '/mypage/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appLayoutRoute: typeof appLayoutRoute
  appDashboardRoute: typeof appDashboardRoute
  appMyProfileRoute: typeof appMyProfileRoute
  MypageLayoutRoute: typeof MypageLayoutRoute
  MypageNotificationsRoute: typeof MypageNotificationsRoute
  MypageProfileRoute: typeof MypageProfileRoute
  MypageSettingsRoute: typeof MypageSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/settings': {
      id: '/mypage/settings'
      path: '/mypage/settings'
      fullPath: '/mypage/settings'
      preLoaderRoute: typeof MypageSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/profile': {
      id: '/mypage/profile'
      path: '/mypage/profile'
      fullPath: '/mypage/profile'
      preLoaderRoute: typeof MypageProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/notifications': {
      id: '/mypage/notifications'
      path: '/mypage/notifications'
      fullPath: '/mypage/notifications'
      preLoaderRoute: typeof MypageNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/_layout': {
      id: '/mypage/_layout'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/my-profile': {
      id: '/(app)/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof appMyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appLayoutRoute: appLayoutRoute,
  appDashboardRoute: appDashboardRoute,
  appMyProfileRoute: appMyProfileRoute,
  MypageLayoutRoute: MypageLayoutRoute,
  MypageNotificationsRoute: MypageNotificationsRoute,
  MypageProfileRoute: MypageProfileRoute,
  MypageSettingsRoute: MypageSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
