/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MypageSettingsRouteImport } from './routes/mypage/settings'
import { Route as MypageProfileRouteImport } from './routes/mypage/profile'
import { Route as AppMyProfileRouteImport } from './routes/_app/my-profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'

const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageSettingsRoute = MypageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MypageRoute,
} as any)
const MypageProfileRoute = MypageProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MypageRoute,
} as any)
const AppMyProfileRoute = AppMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mypage': typeof MypageRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/my-profile': typeof AppMyProfileRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/settings': typeof MypageSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mypage': typeof MypageRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/my-profile': typeof AppMyProfileRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/settings': typeof MypageSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/mypage': typeof MypageRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/my-profile': typeof AppMyProfileRoute
  '/mypage/profile': typeof MypageProfileRoute
  '/mypage/settings': typeof MypageSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mypage'
    | '/dashboard'
    | '/my-profile'
    | '/mypage/profile'
    | '/mypage/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mypage'
    | '/dashboard'
    | '/my-profile'
    | '/mypage/profile'
    | '/mypage/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/mypage'
    | '/_app/dashboard'
    | '/_app/my-profile'
    | '/mypage/profile'
    | '/mypage/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MypageRoute: typeof MypageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/settings': {
      id: '/mypage/settings'
      path: '/settings'
      fullPath: '/mypage/settings'
      preLoaderRoute: typeof MypageSettingsRouteImport
      parentRoute: typeof MypageRoute
    }
    '/mypage/profile': {
      id: '/mypage/profile'
      path: '/profile'
      fullPath: '/mypage/profile'
      preLoaderRoute: typeof MypageProfileRouteImport
      parentRoute: typeof MypageRoute
    }
    '/_app/my-profile': {
      id: '/_app/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof AppMyProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMyProfileRoute: typeof AppMyProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMyProfileRoute: AppMyProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MypageRouteChildren {
  MypageProfileRoute: typeof MypageProfileRoute
  MypageSettingsRoute: typeof MypageSettingsRoute
}

const MypageRouteChildren: MypageRouteChildren = {
  MypageProfileRoute: MypageProfileRoute,
  MypageSettingsRoute: MypageSettingsRoute,
}

const MypageRouteWithChildren =
  MypageRoute._addFileChildren(MypageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MypageRoute: MypageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
