/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MypageRouteImport } from './routes/_mypage'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MypageProfileRouteImport } from './routes/_mypage/profile'
import { Route as MypageNotificationsRouteImport } from './routes/_mypage/notifications'
import { Route as AppMyProfileRouteImport } from './routes/_app/my-profile'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'

const MypageRoute = MypageRouteImport.update({
  id: '/_mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageProfileRoute = MypageProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MypageRoute,
} as any)
const MypageNotificationsRoute = MypageNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MypageRoute,
} as any)
const AppMyProfileRoute = AppMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-profile': typeof AppMyProfileRoute
  '/notifications': typeof MypageNotificationsRoute
  '/profile': typeof MypageProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-profile': typeof AppMyProfileRoute
  '/notifications': typeof MypageNotificationsRoute
  '/profile': typeof MypageProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_mypage': typeof MypageRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/my-profile': typeof AppMyProfileRoute
  '/_mypage/notifications': typeof MypageNotificationsRoute
  '/_mypage/profile': typeof MypageProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/my-profile' | '/notifications' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/my-profile' | '/notifications' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_mypage'
    | '/_app/dashboard'
    | '/_app/my-profile'
    | '/_mypage/notifications'
    | '/_mypage/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MypageRoute: typeof MypageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mypage': {
      id: '/_mypage'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mypage/profile': {
      id: '/_mypage/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MypageProfileRouteImport
      parentRoute: typeof MypageRoute
    }
    '/_mypage/notifications': {
      id: '/_mypage/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MypageNotificationsRouteImport
      parentRoute: typeof MypageRoute
    }
    '/_app/my-profile': {
      id: '/_app/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof AppMyProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMyProfileRoute: typeof AppMyProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMyProfileRoute: AppMyProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MypageRouteChildren {
  MypageNotificationsRoute: typeof MypageNotificationsRoute
  MypageProfileRoute: typeof MypageProfileRoute
}

const MypageRouteChildren: MypageRouteChildren = {
  MypageNotificationsRoute: MypageNotificationsRoute,
  MypageProfileRoute: MypageProfileRoute,
}

const MypageRouteWithChildren =
  MypageRoute._addFileChildren(MypageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MypageRoute: MypageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
